// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otaqgrstiogbslwgyynw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90YXFncnN0aW9nYnNsd2d5eW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzgxNjEsImV4cCI6MjA2NzgxNDE2MX0.c_c2UaNjdIKcn0MTypcf4icP2UGAHcGqXSk8uFYtUUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});